<div class="jumbotron" style="margin-top:10px;">
    <h1>Welcome to your ZF2 Cloud!</h1>

    <p>Congratulations! You have successfully installed the PHP OpenCloud skeleton app and can begin creating your very
        own control panel. You can monitor your Servers, your Swift containers, your Database instances; in fact, <em>anything</em>
        you would normally expect from the SDK, but delivered in an easier way.</p>

    <p style="margin-top:20px;">
        <a class="btn btn-danger btn-lg" href="https://github.com/jamiehannaford/php-opencloud-zf2" target="_blank"
           style="margin-right:10px;">View this ZF2 module on Github</a>
        <a class="btn btn-danger btn-lg" href="https://github.com/rackspace/php-opencloud" target="_blank">View
            php-opencloud on Github</a>
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Rackspace Developers</h3>
            </div>
            <div class="panel-body">
                <p>Check out <a href="http://developer.rackspace.com" target="_blank">developer.rackspace.com</a> for
                    our free dev discount and links to all our developer tools.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Rackspace Documentation</h3>
            </div>
            <div class="panel-body">
                <p>Check out our <a href="http://docs.rackspace.com" target="_blank">official documentation</a> pages
                    for Getting Started guides and API docs.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Zend Framework 2</h3>
            </div>
            <div class="panel-body">
                <p>Check out the <a href="http://zendframework.com" target="_blank">official website</a> for Getting
                    Started guides and library docs.</p>
            </div>
        </div>
    </div>
</div>
